name: Build & Publish OCI Image
on: 
  workflow_dispatch:
    inputs:
      tag:
        description: Tag for images
        default: ''
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3

      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Example Notebook Images
        run: |
          cd images/example-notebook-servers/
          make docker-build-all TAG=${{ inputs.tag }}

      - name: Publish Example Notebook Images
        run: |
          cd images/example-notebook-servers/
          make docker-push-all TAG=${{ inputs.tag }} REGISTRY=domfleischmann



